import {escape as esc} from './charts.js';
const n=v=>Number.isFinite(v)?v.toFixed(1):'—';
let filters={mode:'real',kind:'full_swing',metric:'carry',inclusion:'included'},ticket=0;
const options=(items,selected,empty='All')=>`<option value="">${empty}</option>`+items.map(([id,label])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`).join('');
const color=id=>['#1455ed','#087b69','#b76006','#853fbe','#ba3276'][([...id].reduce((h,c)=>h*31+c.charCodeAt(0),0)>>>0)%5];

function trendChart(report) {
  const m=report.filters.metric,rows=report.trend.slice(-24),valid=rows.filter(r=>r.metrics[m].median!=null),W=900,H=340,L=65,R=35,T=30,B=75;
  if(!valid.length)return '<div class="empty">Choose a metric with available readings to see its history.</div>';
  const values=valid.flatMap(r=>[r.metrics[m].q1??r.metrics[m].median,r.metrics[m].q3??r.metrics[m].median]);
  const low=Math.min(...values),high=Math.max(...values),pad=Math.max((high-low)*.15,1),min=low-pad,max=high+pad;
  const x=i=>L+(W-L-R)*(rows.length===1?.5:i/(rows.length-1)),y=v=>T+(H-T-B)*(max-v)/(max-min);
  return `<svg class="analysis-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Session medians and interquartile ranges for ${esc(report.metrics[m].label)}">${[0,.25,.5,.75,1].map(f=>`<line x1="${L}" x2="${W-R}" y1="${y(min+f*(max-min))}" y2="${y(min+f*(max-min))}" class="range-gridline"/><text x="${L-10}" y="${y(min+f*(max-min))+5}" text-anchor="end">${n(min+f*(max-min))}</text>`).join('')}${rows.map((r,i)=>{const s=r.metrics[m];return `${s.median==null?'':`<line x1="${x(i)}" x2="${x(i)}" y1="${y(s.q1??s.median)}" y2="${y(s.q3??s.median)}" stroke="var(--accent)" stroke-width="9" stroke-opacity=".4"/><circle cx="${x(i)}" cy="${y(s.median)}" r="6" fill="var(--accent)"><title>${esc(r.drill)} · ${r.started.slice(0,10)} · median ${n(s.median)} · n=${s.count}</title></circle>`}<text x="${x(i)}" y="${H-45}" text-anchor="middle">${i+1+Math.max(0,report.trend.length-24)}</text>`;}).join('')}<text x="${W/2}" y="${H-9}" text-anchor="middle">Session order · last ${rows.length} matching sessions · ${esc(report.metrics[m].unit)}</text></svg>`;
}
function dispersion(report) {
  const metric=['carry','total'].includes(report.filters.metric)?report.filters.metric:'carry';
  const all=report.rows.filter(r=>Number.isFinite(r.values[metric])&&Number.isFinite(r.values.offline)),rows=all.slice(-500);
  if(!rows.length)return '<div class="empty">No reported distance/offline pairs in this selection.</div>';
  const W=700,H=340,L=65,B=50,T=20,side=Math.max(20,...rows.map(r=>Math.abs(r.values.offline)))*1.15,far=Math.max(50,...rows.map(r=>r.values[metric]))*1.1;
  const x=v=>L+(W-L-30)*(v+side)/(2*side),y=v=>H-B-(H-B-T)*v/far;
  return `<svg class="analysis-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Reported ${metric} versus signed offline">${[0,.5,1].map(f=>`<line x1="${L}" x2="${W-30}" y1="${y(f*far)}" y2="${y(f*far)}" class="range-gridline"/><text x="${L-8}" y="${y(f*far)+5}" text-anchor="end">${Math.round(f*far)}</text>`).join('')}<line x1="${x(0)}" x2="${x(0)}" y1="${T}" y2="${H-B}" class="range-centerline"/>${rows.map(r=>`<circle cx="${x(r.values.offline)}" cy="${y(r.values[metric])}" r="5" fill="${color(r.bag_id+r.club_id)}" opacity="${r.excluded?.3:.85}"><title>${esc(r.bag_name)} / ${esc(r.club_label)} · ${n(r.values[metric])} yd · ${n(r.values.offline)} offline</title></circle>`).join('')}<text x="${L}" y="${H-25}">${Math.round(side)}L</text><text x="${x(0)}" y="${H-25}">0</text><text x="${W-30}" y="${H-25}" text-anchor="end">${Math.round(side)}R</text><text x="${W/2}" y="${H-5}" text-anchor="middle">Offline · yd / vertical ${metric} · yd</text></svg><p class="form-hint">${rows.length}/${all.length} available pairs shown (up to 500). Reported offline endpoint is unverified; this is not a validated landing map.</p>`;
}

export async function renderAnalyze(app,api,notice,isCurrent) {
  const request=++ticket;
  app.innerHTML='<div class="page-head"><h1>Analyze</h1><button class="btn quiet" data-action="home">← Practice</button></div><section class="card" role="status">Loading saved sessions…</section>';
  try {
    const report=await api('/api/analysis?'+new URLSearchParams(filters));
    if(request!==ticket||!isCurrent())return;
    filters=report.filters;
    draw(app,report,api,notice,isCurrent);
  } catch(e){if(request!==ticket||!isCurrent())return;app.innerHTML='<div class="page-head"><h1>Analyze</h1><button class="btn quiet" data-action="home">← Practice</button></div><section class="card"><p role="alert">Could not load this analysis.</p><button class="btn" data-analysis-reset>Reset filters and retry</button></section>';app.querySelector('[data-analysis-reset]').onclick=()=>{filters={};renderAnalyze(app,api,notice,isCurrent);};notice(e.message);}
}
function draw(app,r,api,notice,isCurrent) {
  const f=r.filters,m=r.metrics[f.metric],s=r.selected[f.metric],all=r.all_recorded[f.metric];
  const columns=[...new Set([f.metric,'carry','total','absolute_offline','launch_ang','total_spin','descent_ang'])];
  const sessionIds=f.sessions.split(',');
  app.innerHTML=`<div class="page-head"><div><p class="eyebrow">YOUR GAME / OVER TIME</p><h1>Analyze</h1><p class="subtitle">Compare sessions, equipment and swing intent.</p></div><button class="btn quiet" data-action="home">← Practice</button></div>${f.mode==='demo'?'<section class="range-demo"><strong>SIMULATED DATA · Demo sessions only</strong></section>':''}<form id="analysis-filters" class="card"><div class="analysis-filters"><label class="field">Data<select name="mode"><option value="real" ${f.mode==='real'?'selected':''}>Real sessions</option><option value="demo" ${f.mode==='demo'?'selected':''}>Demo sessions only</option></select></label><label class="field">Practice type<select name="kind">${[['full_swing','Full swing'],['putting','Putting'],['game','Simulator rounds'],['all','All types']].map(([id,label])=>`<option value="${id}" ${id===f.kind?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">From session date<input type="date" name="date_from" value="${esc(f.date_from)}"></label><label class="field">Through session date<input type="date" name="date_to" value="${esc(f.date_to)}"></label><label class="field">Bag<select name="bag">${options(Object.entries(r.options.bags),f.bag)}</select></label><label class="field">Club<select name="club">${options(Object.entries(r.options.clubs).filter(([,c])=>!f.bag||c.bag===f.bag).map(([id,c])=>[id,c.label+' / '+r.options.bags[c.bag]]),f.club)}</select></label><label class="field">Swing intent<select name="swing">${options([['__unspecified','Unspecified / general practice'],...r.options.swings.map(l=>[l,l])],f.swing)}</select></label><label class="field">Focus metric<select name="metric">${Object.entries(r.metrics).map(([id,m])=>`<option value="${id}" ${id===f.metric?'selected':''}>${m.label} · ${m.unit}</option>`).join('')}</select></label><label class="field">Analysis scope<select name="inclusion"><option value="included" ${f.inclusion==='included'?'selected':''}>Included shots</option><option value="all" ${f.inclusion==='all'?'selected':''}>All non-removed shots</option></select></label></div><details class="details section-space"><summary>Select sessions to compare (${sessionIds.filter(Boolean).length||'all'})</summary><div class="analysis-session-picks">${r.options.sessions.map(x=>`<label class="collection-option"><input type="checkbox" name="sessions" value="${x.id}" ${sessionIds.includes(x.id)?'checked':''}>${esc(x.started.slice(0,10))} · ${esc(x.drill)} · ${x.id.slice(0,6)}</label>`).join('')||'<p>No saved sessions in this data/type selection.</p>'}</div><p class="form-hint">No checked sessions means all matching sessions.</p></details><div class="form-foot"><button class="btn primary" type="submit">Apply / refresh</button><button class="btn quiet" type="button" data-reset>Reset filters</button><a class="btn" href="/api/analysis?${esc(new URLSearchParams({...f,format:'csv'}).toString())}" download>Export filtered shots CSV</a></div></form>
  <div class="analysis-stats section-space"><section class="card"><span>${esc(m.label)} median</span><strong>${n(s.median)} <small>${esc(m.unit)}</small></strong><small>n=${s.count} available / ${r.count} selected</small></section><section class="card"><span>Middle 50% · IQR</span><strong>${n(s.iqr)} <small>${esc(m.unit)}</small></strong><small>Q1 ${n(s.q1)} / Q3 ${n(s.q3)}</small></section><section class="card"><span>All non-removed median</span><strong>${n(all.median)} <small>${esc(m.unit)}</small></strong><small>n=${all.count} · includes excluded shots</small></section><section class="card"><span>Excluded from analysis</span><strong>${r.eligible?n(100*r.excluded/r.eligible):'—'}<small>%</small></strong><small>${r.excluded}/${r.eligible} eligible attempts · ${r.removed} removed</small></section></div>
  <p class="form-hint section-space">Manual exclusion rate is not an outlier or mishit rate. ${esc(r.counting)} Deleted sessions are omitted. Date filters use each session’s recorded start date.</p>
  <div class="analysis-charts"><section class="card"><h2>${esc(m.label)} over sessions</h2><p class="form-hint">Dots = median; bars = Q1–Q3. ${r.groups.length>1?'Mixed clubs/intents: narrow the filters before interpreting a change as improvement.':'Compare similar conditions; these values are not normalized for weather or ball type.'}</p>${trendChart(r)}</section><section class="card"><h2>Shot distribution</h2>${dispersion(r)}</section></div>
  <section class="card section-space"><h2>Equipment and swing comparison</h2><p class="form-hint">Groups preserve bag/club identities and separate swing labels. Each cell is median / IQR with its own available count. Missing readings stay unavailable.</p><div class="table-wrap"><table><thead><tr><th>Bag / club / swing</th>${columns.map(k=>`<th>${esc(r.metrics[k].label)} · ${r.metrics[k].unit}</th>`).join('')}</tr></thead><tbody>${r.groups.map(g=>`<tr><th><svg width="12" height="12" aria-hidden="true"><circle cx="6" cy="6" r="5" fill="${color(g.bag_id+g.club_id)}"/></svg> ${esc(g.bag_name)} / ${esc(g.club_label)}<small class="range-stat-detail">${esc(g.swing_label||'Unspecified / general practice')}</small></th>${columns.map(k=>`<td>${n(g.metrics[k].median)} / ${n(g.metrics[k].iqr)}<small class="range-stat-detail">n=${g.metrics[k].count}</small></td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length+1}" class="empty">No matching shots. Change filters or collect a session.</td></tr>`}</tbody></table></div></section>
  <section class="card section-space"><h2>Session comparison and review</h2><div class="table-wrap"><table><thead><tr><th>Session</th><th>Selected attempts</th><th>${esc(m.label)} median / IQR · ${esc(m.unit)}</th><th>Excluded / eligible</th><th>Review</th></tr></thead><tbody>${r.trend.map((t,i)=>`<tr><th>${i+1} · ${esc(t.started.slice(0,10))}<small class="range-stat-detail">${esc(t.drill)}</small></th><td>${t.count}</td><td>${n(t.metrics[f.metric].median)} / ${n(t.metrics[f.metric].iqr)} · n=${t.metrics[f.metric].count}</td><td>${t.excluded}/${t.eligible}</td><td><a class="btn small" href="#sessions/${t.id}">Review session</a></td></tr>`).join('')||'<tr><td colspan="5">No matching sessions.</td></tr>'}</tbody></table></div><p class="form-hint">${esc(r.method)} Filtered export contains source readings and session/equipment/swing context. No measured data is rewritten.</p></section>`;
  const form=app.querySelector('form');
  form.onsubmit=e=>{e.preventDefault();const data=new FormData(form);filters={...Object.fromEntries(data),sessions:data.getAll('sessions').join(',')};renderAnalyze(app,api,notice,isCurrent);};
  form.querySelector('[data-reset]').onclick=()=>{filters={};renderAnalyze(app,api,notice,isCurrent);};
  form.elements.bag.onchange=()=>{form.elements.club.innerHTML=options(Object.entries(r.options.clubs).filter(([,c])=>!form.elements.bag.value||c.bag===form.elements.bag.value).map(([id,c])=>[id,c.label]),'');};
  for(const k of ['mode','kind'])form.elements[k].onchange=()=>{filters={mode:form.elements.mode.value,kind:form.elements.kind.value,metric:f.metric,inclusion:f.inclusion};renderAnalyze(app,api,notice,isCurrent);};
}
