import {escape as esc} from './charts.js';
import {courseLayers} from './course-art.js';
import {editorMarkup,bindEditor} from './course-editor.js';
let draft=null,source=null,inspection=null,lastParams=null,draftId=null,draftRevision=0;
let history=[],dirty=false,workingEdits=null,settingsDraft=null,pendingDrawing=false;
if(typeof window!=="undefined")window.addEventListener("beforeunload",e=>{if(dirty||pendingDrawing){e.preventDefault();e.returnValue="";}});
export function importMap(c) {
  return `<svg class="game-map import-map" viewBox="${c.viewbox.join(' ')}" role="img" aria-label="Imported hole preview and scoring boundaries">${courseLayers(c,{detailed:false,boundaries:true})}<polyline points="${(c.playing_line??[[0,0],c.pin]).map(p=>`${p[1]},${p[0]}`).join(' ')}" fill="none" stroke="#fff" stroke-dasharray="3 3" stroke-width=".8"/><circle cx="${c.tee?.[1]??0}" cy="${c.tee?.[0]??0}" r="3" fill="#fff"/><text x="${(c.tee?.[1]??0)+5}" y="${(c.tee?.[0]??0)-5}" font-size="6" fill="#fff">TEE</text><circle cx="${c.pin[1]}" cy="${c.pin[0]}" r="3" fill="#32e2bf"/><text x="${c.pin[1]}" y="${c.pin[0]-6}" font-size="6" fill="#fff">PIN</text></svg>`;
}
export function renderCourseImport(app,api,notice,published,current) {
  app.innerHTML=`<div class="page-head"><div><p class="eyebrow">PLAY / COURSE LIBRARY</p><h1>Bring a hole into TraceLoft</h1><p class="subtitle">Load a hole. Correct its boundaries. Save a draft or publish a playable version.</p></div><button class="btn quiet" data-action="play">← Play</button></div>
  <section class="card import-drafts"><div><p class="eyebrow">YOUR COURSE WORKBENCH</p><h2>Pick up where you left off</h2><p class="form-hint">Saved drafts stay on this server and are included in database backups. Publishing adds a fixed version to Play.</p></div><div class="form-grid"><label class="field">Saved draft<select id="draft-list"><option value="">Loading drafts…</option></select></label><div class="form-foot"><button class="btn" id="draft-open">Open draft</button><button class="btn quiet" id="draft-new">New import</button></div></div></section>
  <div class="import-layout"><section class="card"><p class="eyebrow">01 / SOURCE</p><h2>Start with a mapped course</h2><p>Download OpenStreetMap geometry, or open a GeoJSON / Overpass JSON export. Only the course identifier is sent to the public map service.</p><form id="course-download"><label class="field">OpenStreetMap course link or way ID<input name="way" placeholder="https://www.openstreetmap.org/way/…" required></label><div class="form-foot"><button class="btn primary" type="submit">Get mapped course</button><button class="btn quiet" type="button" id="course-pilot">Open Jackson Park example</button></div></form><p class="form-hint">Bundled Seattle example · map snapshot October 2, 2026. Works offline; incomplete geometry, not a verified reconstruction.</p><label class="field section-space">Or open a geometry file<input id="course-file" type="file" accept=".json,.geojson,application/json"></label><p class="form-hint">Geometry: maximum 2 MB · WGS84 coordinates · polygons plus golf=hole paths. Also accepts exported TraceLoft draft JSON (up to 4 MB). Export OSM multipolygon relations as GeoJSON.</p><p id="course-source-status" role="status"></p><details class="details"><summary>How to prepare a source</summary><p>Export golf=hole LineStrings and golf=green/fairway/tee/bunker polygons, with natural=water/wood areas. Each hole path runs from its tee to the green. GeoJSON properties keep those tags. Preview even incomplete holes, then draw missing surfaces or correct vertices in the map editor. Tee and pin must be inside the game boundary, and the pin must lie on a green before publication.</p><p>Use data you can reuse. Attribution follows the saved course. Artwork and elevation are separate steps.</p></details></section>
  <section class="card"><p class="eyebrow">02 / HOLE & SCALE</p><h2>Choose your pilot hole</h2><form id="course-settings"><div class="form-grid"><label class="field">Mapped hole<select name="hole_id" required></select></label><label class="field">Course / hole name<input name="name" value="Imported course" maxlength="100" required></label><label class="field">Par<input name="par" type="number" min="3" max="6" value="4" required></label><label class="field">Scorecard length · yd (optional)<input name="scorecard_yards" type="number" min="30" max="1000" step=".1"></label><label class="field">Tee label<input name="tee_label" value="Mapped tee · unverified" maxlength="80" required></label><label class="field">Source / scorecard link<input name="source_url" type="url" maxlength="500"></label></div><p class="form-hint">Scale comes from geographic coordinates. Scorecard yardage is a cross-check; it never stretches the map.</p><button class="btn primary section-space" type="submit" id="course-preview" disabled>Preview boundaries →</button></form></section></div>
  <section id="course-preview-panel" class="card section-space" hidden></section>`;
  const form=app.querySelector('#course-settings'),status=app.querySelector('#course-source-status'),panel=app.querySelector('#course-preview-panel');
  const showSource=()=>{if(!inspection)return;form.elements.hole_id.innerHTML=inspection.holes.map(h=>`<option value="${esc(h.id)}">${esc(h.label)}</option>`).join('');form.elements.par.value=Number(inspection.holes[0]?.par)||4;app.querySelector('#course-preview').disabled=false;status.textContent=`${inspection.holes.length} mapped hole paths available. Preview before saving.`;};
  const resetPreview=()=>{pendingDrawing=false;draft=null;lastParams=null;history=[];dirty=true;panel.hidden=true;};
  const showPreview=()=>{
    if(!draft)return;pendingDrawing=false;const c=draft,p=c.provenance;panel.hidden=false;
    panel.innerHTML=`<div class="table-head"><div><p class="eyebrow">03 / CORRECT & REVIEW</p><h2>${esc(c.name)}</h2></div><span class="chip">${dirty?'UNSAVED CHANGES':'SAVED DRAFT'}</span></div><div class="import-preview-grid"><div>${importMap(c)}${editorMarkup(c)}<p class="game-boundary-key">White: fairway · lime: green/tee · gold: sand · cyan: water · purple: nature · pink: artificial game boundary</p><p class="form-hint">${esc(p.attribution)}</p></div><div><div class="game-score"><div><span>Playing-line length</span><strong>${p.route_yards} yd</strong></div><div><span>Straight tee → pin</span><strong>${p.straight_yards} yd</strong></div></div><p class="form-hint">${Object.entries(c.surfaces).map(([k,v])=>`${v.length} ${k}`).join(' · ')}</p><h3>Ready to publish?</h3>${c.blocking_issues?.length?`<div class="import-blockers" role="status"><strong>Corrections needed</strong><ul>${c.blocking_issues.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`:'<p class="import-valid">Geometry checks passed. Review the source and assumptions below.</p>'}<ul class="import-warnings">${c.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul><label class="field check"><input type="checkbox" id="course-reviewed">I checked the tee, pin, yardage and surface edges, and accept the game boundary and prototype rules.</label><button class="btn primary section-space" id="course-save" disabled>Publish hole to Play</button><div class="form-foot"><button class="btn" id="draft-save">Save draft</button><button class="btn quiet" id="draft-export">Export draft JSON</button></div><p id="draft-status" role="status">${dirty?'Local edits are not saved yet.':'Draft saved on this server.'}</p><p class="form-hint">Every geometry edit clears review approval. Saves a fixed version. Existing rounds keep their saved geometry. No session is started.</p></div></div>`;
    const button=panel.querySelector('#course-save');panel.querySelector('#course-reviewed').onchange=e=>button.disabled=!e.target.checked||Boolean(c.blocking_issues?.length);
    const saveDraft=panel.querySelector('#draft-save');
    saveDraft.onclick=async()=>{saveDraft.disabled=true;const sent=lastParams;try{const saved=await api('/api/course-drafts',{params:sent,id:draftId,revision:draftRevision});if(!current()||!panel.isConnected||lastParams!==sent)return;draftId=saved.id;draftRevision=saved.revision;dirty=false;showPreview();await refreshDrafts();notice('Draft saved. You can return later or open it from another device.');}catch(e){notice(e.message);}finally{saveDraft.disabled=false;}};
    panel.querySelector('#draft-export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({format:'traceloft-course-draft-v1',params:lastParams},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='traceloft-course-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
    bindEditor(panel,c,async edits=>{const old=lastParams,params={...lastParams,edits};const next=await api('/api/courses/preview',params);if(!current()||!panel.isConnected||old!==lastParams)return;history.push(old);lastParams=params;workingEdits=params.edits;draft=next;dirty=true;showPreview();},async()=>{if(!history.length)return;const previous=history.at(-1),old=lastParams,next=await api('/api/courses/preview',previous);if(!current()||!panel.isConnected||old!==lastParams)return;history.pop();lastParams=previous;workingEdits=previous.edits??null;draft=next;dirty=true;showPreview();},history.length>0,notice,pending=>{pendingDrawing=pending;for(const id of ["draft-save","draft-export","course-reviewed"])panel.querySelector("#"+id).disabled=pending;button.disabled=pending||!panel.querySelector("#course-reviewed").checked||Boolean(c.blocking_issues?.length);});
    button.onclick=async()=>{button.disabled=true;panel.inert=true;const sent=lastParams;try{const copy=await api('/api/course-drafts',{params:sent,id:draftId,revision:draftRevision});if(!current()||!panel.isConnected||lastParams!==sent)return;draftId=copy.id;draftRevision=copy.revision;dirty=false;const saved=await api('/api/courses/save',{...sent,reviewed:true});await published();if(!current()||!panel.isConnected||lastParams!==sent)return;panel.querySelector('.chip').textContent='PUBLISHED';panel.querySelector('#draft-status').textContent='Draft saved and fixed version published to Play.';button.textContent='Published';panel.querySelector('#course-reviewed').disabled=true;await refreshDrafts();notice(`${saved.name} is in your course library. Choose it in round setup.`);}catch(e){notice(e.message);button.disabled=false;}finally{panel.inert=false;}};
  };
  const receive=(data,meta)=>{draftId=null;draftRevision=0;workingEdits=null;settingsDraft=null;source=data;inspection=meta;resetPreview();showSource();notice(`Loaded ${inspection.holes.length} mapped hole paths. Choose a hole and preview its boundaries.`);};
  const download=async(way)=>{
    if(!confirmReplace())return;
    const match=way.trim().match(/^(?:https:\/\/www\.openstreetmap\.org\/way\/)?(\d+)\/?$/);
    if(!match){notice('Paste an OpenStreetMap way link or numeric way ID.');return;}
    const controls=app.querySelectorAll('#course-download button');controls.forEach(b=>b.disabled=true);status.textContent='Downloading mapped geometry…';
    try{const result=await api('/api/courses/osm',{way_id:Number(match[1])});if(!current()||!panel.isConnected)return;receive(result.data,result);form.elements.source_url.value=`https://www.openstreetmap.org/way/${match[1]}`;const course=result.data.elements.find(e=>e.id===Number(match[1]));form.elements.name.value=course?.tags?.name??'Imported course';}
    catch(e){notice(e.message);status.textContent='Download failed. Try later or open a saved geometry file.';}
    finally{controls.forEach(b=>b.disabled=false);}
  };
  app.querySelector('#course-download').onsubmit=e=>{e.preventDefault();download(e.target.elements.way.value);};
  app.querySelector('#course-pilot').onclick=async e=>{if(!confirmReplace())return;e.target.disabled=true;try{const result=await api('/api/courses/example');if(!current()||!panel.isConnected)return;receive(result.data,result);form.elements.name.value='Jackson Park · Hole 18 · prototype';form.elements.source_url.value='https://www.openstreetmap.org/way/23060588';}catch(err){notice(err.message);}finally{e.target.disabled=false;}};
  const confirmReplace=()=>!(dirty||pendingDrawing)||confirm('Replace the unsaved import in this tab? Save or export the draft first if you want to keep it.');
  async function refreshDrafts(){try{const list=await api('/api/course-drafts');if(!current()||!app.querySelector('#draft-list'))return;app.querySelector('#draft-list').innerHTML='<option value="">Choose a saved draft</option>'+list.map(d=>`<option value="${esc(d.id)}">${esc(d.name)} · revision ${d.revision}</option>`).join('');if(draftId)app.querySelector('#draft-list').value=draftId;}catch(e){notice(e.message);}}
  async function restoreDraft(saved,local=false){const {params}=saved;if(!params||typeof params!=='object')throw Error('Invalid course draft file.');const meta=await api('/api/courses/inspect',{data:params.data}),next=await api('/api/courses/preview',params);if(!current()||!panel.isConnected)return;source=params.data;inspection=meta;showSource();for(const [k,v] of Object.entries(params))if(form.elements[k])form.elements[k].value=v??'';lastParams=params;workingEdits=params.edits??null;settingsDraft=null;draft=next;history=[];draftId=local?null:saved.id;draftRevision=local?0:saved.revision;dirty=local;showPreview();notice(local?'Imported draft file. Save it to keep a server copy.':'Saved draft opened. Review approval is reset.');}
  app.querySelector('#draft-open').onclick=async()=>{const id=app.querySelector('#draft-list').value;if(!id||!confirmReplace())return;try{await restoreDraft(await api('/api/course-drafts/'+id));}catch(e){notice(e.message);}};
  app.querySelector('#draft-new').onclick=()=>{if(!confirmReplace())return;draftId=null;draftRevision=0;source=null;inspection=null;workingEdits=null;settingsDraft=null;resetPreview();dirty=false;form.reset();form.elements.hole_id.innerHTML='';app.querySelector('#course-preview').disabled=true;status.textContent='Choose a new course source.';};
  app.querySelector('#course-file').onchange=async e=>{const file=e.target.files[0];if(!file||!confirmReplace())return;try{if(file.size>4000000)throw Error('Use a source under 2 MB or a draft under 4 MB.');const data=JSON.parse(await file.text());if(data.format==='traceloft-course-draft-v1')await restoreDraft(data,true);else{const meta=await api('/api/courses/inspect',{data});if(current()&&panel.isConnected)receive(data,meta);}}catch(err){notice(err.message);}};
  refreshDrafts();
  form.oninput=()=>{settingsDraft=Object.fromEntries(new FormData(form));resetPreview();};
  form.elements.hole_id.onchange=()=>{workingEdits=null;draftId=null;draftRevision=0;resetPreview();form.elements.par.value=Number(inspection?.holes.find(h=>h.id===form.elements.hole_id.value)?.par)||4;settingsDraft=Object.fromEntries(new FormData(form));};
  form.onsubmit=async e=>{e.preventDefault();if(!source)return;const f=new FormData(form),params=Object.fromEntries(f.entries());params.par=Number(params.par);params.scorecard_yards=params.scorecard_yards?Number(params.scorecard_yards):null;params.data=source;params.edits=workingEdits;const b=app.querySelector('#course-preview');b.disabled=true;try{const result=await api('/api/courses/preview',params);if(!current()||!panel.isConnected)return;draft=result;lastParams=params;dirty=true;history=[];showPreview();panel.scrollIntoView({behavior:'smooth',block:'start'});}catch(err){notice(err.message);}finally{b.disabled=false;}};
  showSource();if(settingsDraft||lastParams){for(const [k,v] of Object.entries(settingsDraft||lastParams))if(k!=='data'&&form.elements[k])form.elements[k].value=v??'';}showPreview();
}
