import {mountClubPreview} from './club-preview.js';
import {courseLayers} from './course-art.js';
import {escape as esc} from './charts.js';
import {equipmentControls,bindEquipment} from './equipment.js';
import {recordingWarnings} from './recording.js';
const n=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const xy=p=>`${p[1]},${p[0]}`;
let zoomChoice=null,zoomSession=null;
let mapBoundaries=false,mapDetailed=true;

export function gameScoreboard(data) {
  const g=data.game,par=data.course.par,played=data.shots.filter(s=>s.game_outcome?.applied).length;
  const relative=g.strokes-par;
  const result=relative===0?'Par':relative===-1?'Birdie':relative===-2?'Eagle':relative===1?'Bogey':relative===2?'Double bogey':'Hole complete';
  const status=g.holed?`${result} · ${relative>0?'+':''}${relative===0?'E':relative}`:data.ended?'Partial score':'In progress';
  return `<section class="game-scoreboard" aria-label="Hole score"><div class="game-score-heading"><strong>Hole ${esc(String(data.course.hole_number??1))} · Par ${par}</strong><span>${status}</span></div><dl class="game-score-counts"><div class="game-score-total"><dt>Total strokes</dt><dd>${g.strokes}</dd></div><div><dt>Shots played</dt><dd>${played}</dd></div><div><dt>Penalties</dt><dd>${g.penalties}</dd></div><div><dt>Gimme putts</dt><dd>${g.concessions}</dd></div></dl>${g.concessions?`<p class="game-gimme-note">${played} played + ${g.penalties} penalty + ${g.concessions} gimme = ${g.strokes} strokes. The gimme counts the final, unplayed putt.</p>`:''}</section>`;
}

export function aimReadout(data) {
  const {game:g,course:c}=data,feet=g.lie==='green',factor=feet?3:1,unit=feet?'ft':'yd';
  return `<div class="game-aim-distances" role="status" aria-label="Selected aim distances"><div><span>Ball → aim</span><strong>${n(dist(g.position,g.aim)*factor)} <small>${unit}</small></strong></div><div><span>Aim → pin</span><strong>${n(dist(g.aim,c.pin)*factor)} <small>${unit}</small></strong></div></div>`;
}

export function courseMap(data,interactive=false,zoom=false,display={}) {
  const c=data.course,g=data.game,p=c.pin;
  const bounds=zoom?`${p[1]-24} ${p[0]-24} 48 48`:(c.viewbox??[-20,-85,410,170]).join(' ');
  const scale=zoom?.45:(c.viewbox?.[2]??410)/420;
  return `<svg class="game-map ${zoom?'zoomed':''}" viewBox="${bounds}" role="img" aria-label="${esc(c.name)} course, ball and saved shot endpoints${interactive?'. Tap to aim; keyboard aim controls are below.':''}">
    ${courseLayers(c,display)}
    <g id="club-preview-layer" aria-label="Historical mapped dispersion" pointer-events="none"></g>
    ${data.shots.filter(s=>s.game_outcome?.applied).map((s,i)=>{const o=s.game_outcome;return `<line x1="${o.before.position[1]}" y1="${o.before.position[0]}" x2="${o.endpoint[1]}" y2="${o.endpoint[0]}" stroke="${o.penalty_strokes?'#ffad80':'#d8ece3'}" stroke-width="${scale*.65}" stroke-dasharray="2 2" opacity=".65"/><circle cx="${o.endpoint[1]}" cy="${o.endpoint[0]}" r="${scale*1.6}" fill="${o.penalty_strokes?'#ffad80':'#fff'}"><title>Shot ${data.shots.indexOf(s)+1}: ${esc(o.message)}</title></circle>`;}).join('')}
    ${!data.ended?`<line x1="${g.position[1]}" y1="${g.position[0]}" x2="${g.aim[1]}" y2="${g.aim[0]}" stroke="#32e2bf" stroke-width="${scale*.8}" stroke-dasharray="2 2"/><circle cx="${g.aim[1]}" cy="${g.aim[0]}" r="${scale*3}" fill="none" stroke="#32e2bf" stroke-width="${scale*.8}"/>`:''}
    <circle cx="${p[1]}" cy="${p[0]}" r="${scale*1}" fill="#16382c"/>
    <path d="M ${p[1]},${p[0]} v${-scale*10} l${scale*6},${scale*2} l${-scale*6},${scale*2}" fill="#fff" stroke="#fff" stroke-width="${scale*.6}"/>
    <circle cx="${g.position[1]}" cy="${g.position[0]}" r="${scale*3.3}" fill="#153330" stroke="#32e2bf" stroke-width="${scale*1}"/>
    <circle cx="${g.position[1]}" cy="${g.position[0]}" r="${scale*1.6}" fill="#fff"/>
    ${zoom?'':`<text x="${c.tee[1]}" y="${c.tee[0]-18}" fill="#fff" font-size="${scale*5}">TEE</text><text x="${c.pin[1]}" y="${c.pin[0]-27}" text-anchor="middle" fill="#fff" font-size="${scale*5}">PAR ${c.par} · ${c.yards} YD</text>`}
  </svg>`;
}

export function renderPlay(app,state,courses=[]) {
  app.innerHTML=`<div class="page-head"><div><p class="eyebrow">PLAY / COURSE LIBRARY</p><h1>A little golf. A lot to learn.</h1><p class="subtitle">Bring your range shots onto a simple 2D course.</p></div><button class="btn quiet" data-action="home">← Practice</button></div>
  ${state.practice&&!state.practice.ended?'<section class="card section-space"><h2>You have an active session</h2><p>Return to it, then finish or abandon before starting a round.</p><button class="btn primary" data-action="return">Return to active session</button></section>':''}
  <p class="form-hint">Choose a fictional hole. Each round plays one hole with flat-green putting, adjustable lie effects and your bag's historical dispersion. Yardage follows the playing route; map distances are straight line.</p>
  <div class="game-library">${courses.filter(c=>!c.imported).map(c=>`<section class="card game-hole-card">
    ${/^\/assets\/art\/[a-z0-9._-]+$/i.test(c.image??'')?`<img src="${esc(c.image)}" alt="${esc(c.name)} aerial layout" width="1774" height="887">`:''}
    <div class="game-hole-copy"><p class="eyebrow">FICTIONAL HOLE · PAR ${c.par} · ${c.yards} YD</p><h2>${esc(c.name)}</h2><p>${esc(c.description??'Original flat-green golf hole.')}</p><button class="btn primary" data-action="choose" data-drill="golf-sim" data-course="${esc(c.id)}" aria-label="Set up ${esc(c.name)}" ${state.practice&&!state.practice.ended?'disabled':''}>Set up round →</button></div>
  </section>`).join('')}</div>`;
  if(courses.some(c=>c.imported))app.insertAdjacentHTML('beforeend',`<section class="card section-space"><h2>Imported holes</h2><div class="session-list">${courses.filter(c=>c.imported).map(c=>`<div class="session-entry"><div><strong>${esc(c.name)}</strong><p>Par ${c.par} · ${c.yards} yd · reviewed prototype geometry</p></div><button class="btn" data-action="choose" data-drill="golf-sim" data-course="${esc(c.id)}" ${state.practice&&!state.practice.ended?'disabled':''}>Set up this hole →</button></div>`).join('')}</div></section>`);
  app.insertAdjacentHTML('beforeend',`<div class="form-foot section-space"><a class="btn" href="#play/import">Import a course →</a><span class="form-hint">Review one mapped hole, then add it to your course library.</span></div><section class="card section-space"><h2>Try a Tour reference bag</h2><p>Load demo bag mapping and a wedge matrix to explore club suggestions. Full-swing averages come from Trackman’s 2023 Tour dataset; dispersion, rollout and partial wedges are synthetic.</p><button class="btn" data-action="tour-demo">Load Tour demo bag</button><p class="form-hint">Creates two saved demo sessions once. Your bags and active session stay intact. Select “Tour reference · DEMO” in a demo round. <a href="https://www.trackman.com/blog/introducing-updated-tour-averages" target="_blank" rel="noopener">Source and context ↗</a></p></section>`);
}

export function renderGameSetup(app,old,launch,notice,equipment,courses=[]) {
  const s=old.game_settings??{},number=(label,name,value,min,max,step=1)=>`<div class="field"><label for="${name}">${label}</label><div class="game-slider"><input type="range" aria-label="${label} slider" data-slider="${name}" value="${value}" min="${min}" max="${max}" step="${step}"><input id="${name}" type="number" name="${name}" value="${value}" min="${min}" max="${max}" step="${step}" required></div></div>`;
  app.innerHTML=`<div class="page-head"><div><p class="eyebrow">PLAY / ROUND SETUP</p><h1>Make it your round</h1><p class="subtitle">Choose a hole from your library · flat-green endpoint game</p></div><button class="btn quiet" data-action="play">← Play</button></div><form class="card" id="game-setup"><div class="form-grid"><label class="field">Course / hole<select name="game_course_id">${courses.map(c=>`<option value="${esc(c.id)}" ${c.id===(old.course?.id??'meadow-one-v2')?'selected':''}>${esc(c.name)} · par ${c.par} · ${c.yards} yd${c.imported?' · imported':''}</option>`).join('')}</select></label><label class="field">Shot source<select name="demo"><option value="true">Demo · simulated shots</option><option value="false">Live capture · experimental</option></select></label><label class="field">Reported total geometry<select name="game_geometry"><option value="downrange" ${s.geometry==='downrange'?'selected':''}>Downrange + signed offline</option><option value="radial" ${s.geometry==='radial'?'selected':''}>Radial distance + signed offline</option></select></label>${number('Rough distance penalty · %','game_rough',s.rough_percent??7,0,60)}${number('Sand distance penalty · %','game_sand',s.sand_percent??20,0,80)}${number('Extra lie variation · ±degrees','game_variation',s.variation_degrees??0,0,10,.5)}${number('Green speed · Stimp','stimp',s.putting?.stimp_ft??10,3,20,.5)}${number('Gimme radius · ft (+1 stroke)','game_gimme',s.gimme_ft??3,0,10,.5)}</div><p class="form-hint">Variation applies to rough, sand and nature only; nature reduces distance by 30%. Water/OB: +1 penalty, replay from the previous position. A gimme adds one putt; endpoint within 0.2 ft is a simulated hole-out. These are game rules, not validated physical coefficients.</p><label class="field check section-space" id="game-ack" hidden><input type="checkbox" name="game_acknowledged">I understand total/offline geometry and right-positive sign are unverified for live source readings. This is an experimental game.</label>${equipmentControls(equipment.catalog(),old.equipment_selection,true)}<div class="form-foot"><button class="btn primary" type="submit">Launch round</button><button class="btn quiet" type="reset">Reset settings</button><button class="btn quiet" data-action="play" type="button">Cancel</button></div></form>`;
  bindEquipment(app,equipment,null);
  const form=app.querySelector('form'),mode=()=>{const live=form.elements.demo.value==='false';app.querySelector('#game-ack').hidden=!live;form.elements.game_acknowledged.required=live;};
  form.querySelectorAll('[data-slider]').forEach(slider=>{const input=form.elements[slider.dataset.slider];slider.oninput=()=>input.value=slider.value;input.oninput=()=>slider.value=input.value;});
  form.elements.demo.onchange=mode;form.onreset=e=>{e.preventDefault();renderGameSetup(app,{},launch,notice,equipment,courses);};
  form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),params={drill:'2D golf',demo:f.get('demo')==='true',game_acknowledged:f.has('game_acknowledged'),game_geometry:f.get('game_geometry'),game_course_id:f.get('game_course_id'),range_bag_id:f.get('range_bag_id'),range_club_id:f.get('range_club_id')};for(const k of ['game_rough','game_sand','game_variation','stimp','game_gimme'])params[k]=Number(f.get(k));try{form.querySelector('[type=submit]').disabled=true;await launch(params);}catch(err){notice(err.message);form.querySelector('[type=submit]').disabled=false;}};
}

export function renderGame(app,data,summary,state,review,sessionNotice,ctx) {
  const g=data.game,c=data.course,s=data.game_settings,active=!review&&!data.ended,green=g.lie==='green',last=data.shots.at(-1)?.game_outcome;
  if(zoomSession!==data.id){zoomSession=data.id;zoomChoice=null;}
  const zoom=zoomChoice??green,remaining=summary.remaining_yd,penalty=s[g.lie+'_percent']??0;
  app.innerHTML=`<div class="page-head"><div><p class="eyebrow">${data.demo?'DEMO / ':''}PLAY · ${review?'SAVED REVIEW':data.ended?'ROUND ENDED':'ACTIVE ROUND'}</p><h1>${esc(c.name)}</h1><p class="subtitle">Hole ${esc(String(c.hole_number??1))} · par ${c.par} · ${c.yards} yd <span class="chip">GAME ESTIMATE</span></p></div><div class="head-actions">${active?'<button class="btn danger" data-action="finish">End round</button>':''}<button class="btn quiet" data-action="play">Play menu</button><button class="btn ${active?'quiet':'primary'}" data-action="exit-session">${review?'Exit review':'Exit round'}</button>${!active?'<button class="btn quiet" data-action="edit">New round / edit setup</button>':''}</div></div>
  ${data.demo?`<div class="range-demo" role="status"><strong>SIMULATED DATA · Demo round</strong><span>${active?'Use the shot generator. Live capture does not enter this round.':'Saved synthetic shots. This round has ended.'}</span></div>`:''}
  ${!active?sessionNotice(data,review):''}${state.practice_error&&active?`<p class="session-error" role="alert">${esc(state.practice_error)}</p>`:''}
  ${active&&!data.demo?`<div id="recording-feedback">${recordingWarnings(state.capture,'shots')}</div><div class="form-foot"><button class="btn small" data-action="relay">Relay</button><span class="form-hint">${green?'Putting: speed and start line.':'Full swing: total distance and signed offline required.'}</span></div>`:''}
  ${active?`<section class="card equipment-card game-equipment section-space">${equipmentControls(state.equipment,data.equipment_selection)}</section>`:''}
  <div class="game-layout section-space"><section class="card game-course"><div class="table-head"><h2>${zoom?'Green view':'Hole overview'}</h2><div class="segmented"><button class="btn small ${!zoom?'primary':''}" data-game-zoom="hole">Hole</button><button class="btn small ${zoom?'primary':''}" data-game-zoom="green">Green</button></div></div>${gameScoreboard(data)}${active?aimReadout(data):''}${courseMap(data,active,zoom,{detailed:mapDetailed,boundaries:mapBoundaries})}<div class="game-map-key"><span>● Ball</span><span>⊕ Aim</span><span>Water</span><span>Sand</span><span>Dashed lines connect saved endpoints</span></div>${active?`<p class="form-hint">Tap the map to measure and aim. Distances are straight-line, before lie adjustments. Aim resets to the pin after each move.</p><div class="game-aim"><button class="btn" data-game-aim="pin">Aim at pin</button></div><details class="details"><summary>Enter aim coordinates</summary><form id="game-aim-form" class="game-aim-form"><label class="field">Aim right (+) / left (−) · yd<input name="x" type="number" min="${c.bounds[0]}" max="${c.bounds[1]}" step="any" value="${n(g.aim[0])}" required></label><label class="field">Aim down course · yd<input name="y" type="number" min="${c.bounds[2]}" max="${c.bounds[3]}" step="any" value="${n(g.aim[1])}" required></label><button class="btn" type="submit">Set aim</button></form></details>`:''}${c.provenance?.attribution?`<p class="form-hint">${esc(c.provenance.attribution)}${c.provenance.license_url?' · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">License ↗</a>':''}</p>`:''}<details class="details game-map-display"><summary>Map display</summary><label class="field check"><input type="checkbox" data-map-detailed ${mapDetailed?'checked':''}>Detailed terrain</label><label class="field check"><input type="checkbox" data-map-boundaries ${mapBoundaries?'checked':''}>Show scoring boundaries</label><p class="form-hint">${c.image?'AI-generated artwork':'Imported or schematic map'}; saved course geometry determines the lie. Trees are scenery within nature areas, not individual collision obstacles.</p>${mapBoundaries?'<p class="game-boundary-key">White: fairway · lime: green/tee · gold: sand · cyan: water · purple: nature · pink: out of bounds</p>':''}</details></section>
  <aside class="game-panel"><section id="club-preview" class="card club-preview" aria-label="Club dispersion preview"></section><section class="card game-position"><p class="eyebrow">${g.holed?(g.concessions?'GIMME · FINAL DISTANCE':'HOLE COMPLETE'):'TO THE PIN'}</p><strong class="game-distance">${n(green?remaining*3:remaining)} <small>${green?'ft':'yd'}</small></strong><div class="game-score"><div><span>${g.holed?'Final lie':'Current lie'}</span><strong>${esc(g.lie)}</strong></div>${active?`<div><span>Next stroke</span><strong>${g.strokes+1}</strong></div>`:''}</div>${green&&!g.holed?`<div class="target-tile"><small>NEEDED PACE · ESTIMATED</small><strong>${n(summary.required_pace_mph,2)} mph</strong><p>Flat green · Stimp ${s.putting.stimp_ft}</p></div>`:`<p class="form-hint">Starting-lie distance reduction: ${penalty}%. Extra variation ±${penalty?s.variation_degrees:0}°.</p>`}<p class="game-feedback ${last&&!last.applied?'session-error':''}" role="status">${esc(g.last_message)}</p>${data.ended&&!g.holed?'<p class="miss-text">Round ended before the hole was completed. Score is partial.</p>':''}</section>
  ${active&&data.demo?`<form class="card" id="game-demo"><h2>Simulate a ${green?'putt':'shot'}</h2><p class="form-hint">Explicit synthetic input. Lie adjustments apply after this value.</p><label class="field">${green?'Roll distance · ft':'Reported total · yd'}<input name="distance" type="number" min=".5" max="${green?300:600}" step=".1" value="${n(green?remaining*3:Math.min(200,remaining))}" required></label><label class="field section-space">Offline · ${green?'ft':'yd'} (right +)<input name="offline" type="number" min="${green?-100:-200}" max="${green?100:200}" step=".1" value="0" required></label><button type="submit" class="btn primary section-space">Simulate ${green?'putt':'shot'}</button></form>`:''}
  <section class="card"><h2>Bag suggestions</h2><div id="game-suggestions"><p class="form-hint">${green?(active?'Choose your putter. Pace uses the flat-green estimate.':'Saved round · putting used the recorded Stimp and model.'):'Loading your bag mapping and wedge matrix…'}</p></div></section></aside></div>

  <section class="card section-space"><h2>Round shot log</h2><p class="form-hint">Original shots remain intact. Excluding a shot affects Analyze only; the played position, strokes and penalties stay in the score.</p><div class="table-wrap"><table><thead><tr><th>Attempt / equipment</th><th>Source total / offline</th><th>Speed / start line</th><th>Start → destination</th><th>Game result</th><th>Analyze</th></tr></thead><tbody>${data.shots.map((shot,i)=>{const o=shot.game_outcome;return `<tr class="${shot.excluded?'excluded':''}"><th>${i+1}<small class="range-stat-detail">${esc(shot.bag_name||'No bag')} / ${esc(shot.club_label||'Untagged')}</small></th><td>${n(shot.vals.total)} / ${n(shot.vals.offline)} yd</td><td>${n(shot.vals.ball_speed)} mph / ${n(shot.vals.launch_dir)}°</td><td>${esc(o.before.lie)} → ${esc(o.destination_lie||'unchanged')}</td><td>${esc(o.message)}${o.applied?`<small class="range-stat-detail">Travel ${n(Math.hypot(o.adjusted_forward_yd,o.adjusted_right_yd))} yd · variation ${n(o.random_degrees)}° · total after shot ${o.after.strokes}</small>`:''}</td><td><button class="btn small quiet" data-game-exclude="${esc(shot.key)}">${shot.excluded?'Include':'Exclude'}</button></td></tr>`;}).reverse().join('')||'<tr><td colspan="6" class="empty">Your first shot will appear here.</td></tr>'}</tbody></table></div><div class="table-actions">${active?'<button class="btn danger quiet" data-action="abandon">Abandon round</button>':'<button class="btn danger quiet" data-action="delete-review">Delete round</button>'}<a class="btn quiet" href="#analyze">Analyze sessions</a><button class="btn quiet" data-action="home">Practice selector</button><button class="btn quiet" data-action="exit-session">${review?'Exit review':'Exit round'}</button></div><details class="details"><summary>Game assumptions and saved settings</summary>${c.warnings?`<ul>${c.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:''}<p>Full shots use reported total as ${esc(s.geometry)} distance and positive offline to the right of aim. The final endpoint determines the lie; lines are not flight paths. No bounce, obstacle collision, elevation or wind simulation. Rough ${s.rough_percent}%, sand ${s.sand_percent}%, nature 30%; lie variation ±${s.variation_degrees}°. Water and OB replay with +1. Gimme ${s.gimme_ft} ft adds one putt. Cup acceptance uses a 0.2 ft endpoint window. Putting uses ${esc(s.putting.id)}, Stimp ${s.putting.stimp_ft}; no slope or skid. All rules and random draws are stored per shot.</p></details></section>`;
  mountClubPreview(app,data,state,ctx,active);
  app.querySelectorAll('[data-game-zoom]').forEach(b=>b.onclick=()=>{zoomChoice=b.dataset.gameZoom==='green';ctx.redraw();});
  for(const kind of ['detailed','boundaries'])app.querySelector(`[data-map-${kind}]`).onchange=e=>{if(kind==='detailed')mapDetailed=e.target.checked;else mapBoundaries=e.target.checked;ctx.redraw();app.querySelector('.game-map-display').open=true;app.querySelector(`[data-map-${kind}]`).focus({preventScroll:true});};
  const attempt=async work=>{try{await work();}catch(e){ctx.notice(e.message);}};
  app.querySelectorAll('[data-game-exclude]').forEach(b=>b.onclick=()=>attempt(()=>ctx.exclude(b.dataset.gameExclude)));
  if(active){
    bindEquipment(app,ctx.equipment,ctx.select,ctx.current);
    const aim=(x,y)=>attempt(()=>ctx.aim({x,y,turn:g.turn}));
    const map=app.querySelector('.game-map');map.onclick=e=>{const p=map.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(map.getScreenCTM().inverse());aim(Math.max(c.bounds[0],Math.min(c.bounds[1],q.y)),Math.max(c.bounds[2],Math.min(c.bounds[3],q.x)));};
    app.querySelector('[data-game-aim=pin]').onclick=()=>aim(...c.pin);
    app.querySelector('#game-aim-form').onsubmit=e=>{e.preventDefault();aim(Number(e.target.elements.x.value),Number(e.target.elements.y.value));};
    const demo=app.querySelector('#game-demo');if(demo)demo.onsubmit=e=>{e.preventDefault();const distance=Number(demo.elements.distance.value)/(green?3:1),offline=Number(demo.elements.offline.value)/(green?3:1);demo.querySelector('button').disabled=true;attempt(async()=>{try{await ctx.simulate({distance_yd:distance,offline_yd:offline,turn:g.turn});}finally{if(demo.isConnected)demo.querySelector('button').disabled=false;}});};
  }
  if(!green){const box=app.querySelector('#game-suggestions');ctx.recommendations().then(rows=>{if(!box.isConnected)return;box.innerHTML=rows.length?rows.map(r=>`<p><strong>${esc(r.club_label)}${r.swing_label?' · '+esc(r.swing_label):''}</strong><br>${n(r.adjusted_yd)} yd after lie reduction<small class="range-stat-detail">Total median ${n(r.median_yd)} / IQR ${n(r.iqr_yd)} yd · n=${r.count}</small></p>`).join('')+'<p class="form-hint">From included bag/matrix shots in this bag and data mode; ≥5 readings per club/intent. Nearest distance to the pin; no hazard strategy or weather adjustment.</p>':'<p class="form-hint">No matching profile yet. Collect at least 5 total-distance readings per club/intent in Bag mapping or Wedge matrix. Real and demo profiles stay separate.</p>';}).catch(e=>{if(box.isConnected)box.textContent=e.message;});}
}
